version: "3.9"

services:
    db:
        image: mysql/mysql-server:latest-aarch64
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - wordpress_data:/var/www/html
            - ./wp-content:/var/www/html/wp-content
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

    next:
        ports:
            - 3000:3000
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ./next:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        # entrypoint: ["/bin/bash"]
        # stdin_open: true
        # tty: true

volumes:
    db_data: {}
    wordpress_data: {}
